application:
  darksky:
    language: "pl"
    unitsType: "ca"
    key: "5d11f59a5bb65e816b54f9476d2e21c3"
    forecastDelay: 86400000
spring:
  datasource:
    url: jdbc:postgresql://trainings:5432/appdb
    username: app
    password: Ao4eiT2w
server:
  port: 9090
